version: '3'
services:
  db:
    image: postgres:9.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/go/src/github.com/ablce9/go-assignment
    ports:
      - "5000:5000"
    depends_on:
      - db
